services:
  - type: web
    name: zk-pay
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NEXT_PUBLIC_PRIVY_APP_ID
        sync: false
      - key: SIDESHIFT_AFFILIATE_ID
        sync: false
      - key: NEXT_PUBLIC_DIAMOND_ADDRESS
        sync: false
      - key: NEXT_PUBLIC_USDC_ADDRESS
        sync: false
      - key: NEXT_PUBLIC_CHAIN_ID
        sync: false
      - key: NEXT_PUBLIC_SUBGRAPH_URL
        sync: false
