import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393a",
        "surface-container-lowest": "#0e0e0f",
        "surface-container-low": "#1b1b1d",
        "surface-container": "#201f21",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "on-surface": "#e5e2e3",
        "on-surface-variant": "#c6c6cd",
        "inverse-surface": "#e5e2e3",
        "inverse-on-surface": "#303032",
        "outline": "#909097",
        "outline-variant": "#46464c",
        "surface-tint": "#c0c6de",
        "primary": "#c0c6de",
        "on-primary": "#2a3043",
        "primary-container": "#020617",
        "on-primary-container": "#72778d",
        "inverse-primary": "#585e73",
        "secondary": "#bcc7de",
        "on-secondary": "#263143",
        "secondary-container": "#3e495d",
        "on-secondary-container": "#aeb9d0",
        "tertiary": "#b9c7e0",
        "on-tertiary": "#233144",
        "tertiary-container": "#000715",
        "on-tertiary-container": "#6b798f",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#dce1fb",
        "primary-fixed-dim": "#c0c6de",
        "on-primary-fixed": "#151b2d",
        "on-primary-fixed-variant": "#40465a",
        "secondary-fixed": "#d8e3fb",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary-fixed": "#111c2d",
        "on-secondary-fixed-variant": "#3c475a",
        "tertiary-fixed": "#d5e3fd",
        "tertiary-fixed-dim": "#b9c7e0",
        "on-tertiary-fixed": "#0d1c2f",
        "on-tertiary-fixed-variant": "#3a485c",
        "background": "#131315",
        "on-background": "#e5e2e3",
        "surface-variant": "#353436",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
        display: ["Hanken Grotesk", "system-ui", "sans-serif"],
        "numeric-display": ["Hanken Grotesk"],
        "h1": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "h1-mobile": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "h2": ["Hanken Grotesk"]
      },
      fontSize: {
        "display-xl": ["80px", {"lineHeight": "88px", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "display-xl-mobile": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.15em", "fontWeight": "600"}],
        "numeric-display": ["40px", {"lineHeight": "1", "letterSpacing": "-0.03em", "fontWeight": "300"}],
        "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "h1-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      },
      spacing: {
        "unit": "8px",
        "section-gap": "64px",
        "gutter": "16px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px"
      },
      backdropBlur: {
        glass: "40px",
        "glass-heavy": "60px",
      },
      borderRadius: {
        glass: "12px",
      },
    },
  },
  plugins: [],
};
export default config;
